WebSolution/DSchedule.Web/Controllers/JobGraphController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DSchedule.BusinessComponent;
using DSchedule.Contracts.Models;

namespace DSchedule.Web.Controllers
{
    public class JobGraphController : Controller
    {
        JobMonitorBusinessComponent jobMonitorBusinessComponent = new JobMonitorBusinessComponent();
        JobMonitorModel model = new JobMonitorModel();
        
        // GET: JobGraph
        [HttpGet]
        public ActionResult GraphView(string SessionRunID)
        {
            if (Session["IsJobMonitor"]!=null)
            {
                return RedirectToAction("Index", "JobMonitor");
            }
            if (SessionRunID != null && SessionRunID != "undefined")
            {
                Session["SessionRunID"] = SessionRunID;
            }
            else
            {
                SessionRunID = Session["SessionRunID"].ToString();
            }
            model = jobMonitorBusinessComponent.GetJobSessionGraphDetails(SessionRunID);
            return View(model);
        }

        [HttpPost]
        public ActionResult ProcessAction(string UprocID, string SessionRunID, string UProcStatus)
        {
    
            JobMonitor jobMonitorModel = new JobMonitor();
            jobMonitorModel.UprocID = Convert.ToInt32(UprocID);
            jobMonitorModel.SessionRunID = SessionRunID;
            jobMonitorModel.UProcStatus = UProcStatus;
            switch (jobMonitorModel.UProcStatus)
            {
                case "Start":
                    jobMonitorModel.UProcStatus = "Start";
                    jobMonitorBusinessComponent.UpdateUProcStatusInMSMQ(jobMonitorModel);
                    jobMonitorModel.UProcStatus = "Started";
                    jobMonitorBusinessComponent.UpdateUProcStatusInSession(jobMonitorModel);
                    break;
                case "Re-Run":
                    jobMonitorModel.UProcStatus = "Re-Run";
                    jobMonitorBusinessComponent.UpdateUProcStatusInMSMQ(jobMonitorModel);
                    jobMonitorModel.UProcStatus = "Started";
                    jobMonitorBusinessComponent.UpdateUProcStatusInSession(jobMonitorModel);
                    break;
                case "Re-Schedule":
                    //jobMonitorModel.UProcStatus = "Re-Schedule";
                    jobMonitorBusinessComponent.UpdateUProcStatusInMSMQ(jobMonitorModel);
                    jobMonitorModel.UProcStatus = "Pending";
                    jobMonitorBusinessComponent.UpdateUProcStatusInSession(jobMonitorModel);
                    break;
                case "Hold":
                    jobMonitorModel.UProcStatus = "On Hold";
                    jobMonitorBusinessComponent.UpdateUProcStatusInSession(jobMonitorModel);
                    break;
                case "Abort":
                    jobMonitorModel.UProcStatus = "Aborted";
                    jobMonitorBusinessComponent.UpdateUProcStatusInSession(jobMonitorModel);
                    break;
                case "Force Completion":
                    jobMonitorModel.UProcStatus = "Completed";
                    jobMonitorBusinessComponent.UpdateUProcStatusInSession(jobMonitorModel);
                    break;
                case "Log":
                    // this status should remain the same... as we are just checking the logs.
                    break;
                case "Cancel":
                    jobMonitorModel.UProcStatus = "Cancelled";
                    jobMonitorBusinessComponent.UpdateUProcStatusInSession(jobMonitorModel);
                    break;
            }

            ModelState.Clear();
            model = jobMonitorBusinessComponent.GetJobSessionGraphDetails(SessionRunID);
            return View(model);
      
        }  
    }
  

    
}

WebSolution/DSchedule.Web/Views/JobGraph/GraphView.cshtml
@model DSchedule.Contracts.Models.JobMonitorModel

@{
    ViewBag.Title = "Graph";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Progress Indicator</title>
    <link href="~/Content/indicator.css" rel="stylesheet">
    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/d3.v3.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

</head>
<body ng-app="indicator" oncontextmenu="return false">
    <script language="javascript" type="text/javascript">

        $(document).ready(function () {
            setInterval("location.reload(true)", 10000);
            $(".longString").each(function () {
                var maxwidth = 15;
                if ($(this).text().length > maxwidth) {
                    $(this).text($(this).text().substring(0, maxwidth));
                    $(this).html($(this).html() + '...');
                }
            });
        });
        var sessionrunid;
        var uprocID;
        function ShowMenu(control, e, SessionRunID, UprocID) {
        var posx = e.clientX + window.pageXOffset + 'px'; //Left Position of Mouse Pointer
        var posy = e.clientY + window.pageYOffset + 'px'; //Top Position of Mouse Pointer
        document.getElementById(control).style.position = 'absolute';
        document.getElementById(control).style.display = 'inline';
        document.getElementById(control).style.left = posx;
        document.getElementById(control).style.top = posy;
        sessionrunid = SessionRunID;
        uprocID = UprocID;

    }
    function HideMenu(control) {

        document.getElementById(control).style.display = 'none';
    }
    function Click(action) {
        $.post("/JobGraph/ProcessAction", { UprocID: uprocID, SessionRunID: sessionrunid, UProcStatus: action }, function (data) {
        });
        window.location.href = '@Url.Action("GraphView", "JobGraph")'; 
    }
    </script>
    <script type="text/javascript" src="~/Scripts/indicator.js"></script>
    @{
        var count = Model.JobMonitorList.Count;
     }
    <div class="row">

        @foreach (var item in Model.JobMonitorList)
        {
            var value = "1.0";
            //if (@item.UProcStatus != "Completed")
            //{
            //    value = "0.5";
            //}

            var ProcessName = @item.UprocName.ToString();
            var UProcStatus = @item.UProcStatus.ToString();
            var SessionRunID = @item.SessionRunID.ToString();
            var UprocID = @item.UprocID.ToString();

            <div class="col-lg-3" onmousedown="HideMenu('contextMenu');"
                 onmouseup="HideMenu('contextMenu');"
                 oncontextmenu="ShowMenu('contextMenu', event,'@SessionRunID','@UprocID');">
                <div>
                    <div class="widget-container" style="float:left;"
                         data-expected="1.0"
                         data-actual="@value" data-name="@ProcessName" data-uprocstatus="@UProcStatus" indicator-widget>
                    </div>

                    @{
                        if (count == 1)
                        {


                        }
                        else
                        {
                            <div class="process-container" style="float:right;margin-top:75px;margin-right:-25px;">
                                <img height="40" src="~/Images/arrow.png" />
                            </div>
                        }
                    }
                </div>
            </div>
            count = count - 1;
        }



    </div>

    <script type="text/ng-template" id="indicator.html">
        <svg class="indicator-circle"
             width="200" height="200">
            <g>
                <circle cx="50%" cy="50%" r="60" />
               
                <text class="progress-text longString" text-anchor="middle" alignment-baseline="middle" dx="50%" dy="60%"> {{ name_formatted }}</text>
                <text class="progress-text" text-anchor="middle" alignment-baseline="middle" dx="50%" dy="50%"> {{ uprocstatus_formatted }}</text>
                <text class="tip progress-text" text-anchor="middle" alignment-baseline="middle" dx="50%" dy="98%"> {{ name_formatted }}</text>
                <\br>
            </g>
            <g path-group>
                <path class="progress-bar inner-bar normal" stroke-linejoin="round" inner-path />
            

                @*<path  class="progress-bar outer-bar" stroke-linejoin="round" outer-path />*@
                <path class="progress-bar outer-bar-{{selectcss(uprocstatus_formatted)}}" stroke-linejoin="round" outer-path />

            </g>

        </svg>

    </script>

    <!--
        So we can test this locally without running a server
        otherwise it tries to make an XMLHttpRequest.

        CONS: Not cached.
     -->
    <div style="display:none; background-color:white;" id="contextMenu" class="contextitem">
        <table
               style="border: thin solid #808080; cursor: default; float:left;margin-top:-70px;margin-left:-150px;"
               bgcolor="White">
            <tr>
                <td class="lnkbutton" onclick="javascript: Click('Start')" style="width:80Px">
                    Start
                </td>
            </tr>
            <tr>
                <td class="lnkbutton" onclick="javascript: Click('Re-Run')">
                    Re-Run
                </td>
            </tr>
            <tr>
                <td class="lnkbutton" onclick="javascript: Click('Re-Schedule')">
                    Re-Schedule
                </td>
            </tr>
            <tr>
                <td class="lnkbutton" onclick="javascript: Click('Hold')">
                    Hold
                </td>
            </tr>
            <tr>
                <td class="lnkbutton" onclick="javascript: Click('Abort')">
                    Abort
                </td>
            </tr>
            <tr>
                <td class="lnkbutton" onclick="javascript: Click('Force Completion')">
                    Force Completion
                </td>
            </tr>
            <tr>
                <td class="lnkbutton" onclick="javascript: Click('Cancel')">
                    Cancel
                </td>
            </tr>
        </table>
    </div>




</body>

</html>