WebSolution/DSchedule.Web/Controllers/JobDesignController.cs
using DSchedule.BusinessComponent;
using DSchedule.Contracts;
using DSchedule.Contracts.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Environment = DSchedule.Contracts.Models.Environment;

namespace DSchedule.Web.Controllers
{
    [Authorize]
    public class JobDesignController : Controller
    {
        DScheduleBusinessComponent businessComponent = new DScheduleBusinessComponent();

        #region Nodes
        public ActionResult NodesView()
        {
            try
            {
                NodesModel nm = businessComponent.GetNodes();
                return View("NodesView", nm);
            }
            catch (Exception ex)
            {
                int ErrorId = ErrorLoggingBusinessComponent.SendExcepToDB(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NodesView(NodesModel model)
        {
            try
            {
                Node node = new Node();
                var success = true;
                if (model != null)
                {
                    bool nodeExists = businessComponent.GetNodeList().Any(x => x.NodeName == model.NodeName);
                    if (nodeExists)
                    {
                        model = businessComponent.GetNodes();
                        ModelState.AddModelError("NodeName", "Node already Exists !");
                        return View("NodesView", model);
                    }

                    if (ModelState.IsValid)
                    {
                        node.NodeID = model.NodeID;
                        node.NodeName = model.NodeName;
                        node.NodePath = model.Path;

                        success = businessComponent.SaveNode(node);
                    }
                    else
                    {
                        model = businessComponent.GetNodes();
                        return View(model);
                    }
                }

                return RedirectToAction("NodesView");
            }
            catch (Exception ex)
            {
                int ErrorId = ErrorLoggingBusinessComponent.SendExcepToDB(ex);
                return RedirectToAction("Error", "Home");
            }
        }
        #endregion

        #region Environment
        public ActionResult EnvironmentView()
        {
            try
            {
                EnvironmentModel model = new EnvironmentModel();
                model = businessComponent.GetEnvironments();
                return View("EnvironmentView", model);
            }
            catch (Exception ex)
            {
                int ErrorId = ErrorLoggingBusinessComponent.SendExcepToDB(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EnvironmentView(EnvironmentModel transaction)
        {
            try
            {
                bool nodeExists = transaction.EnvironmentList.Any(x => x.EnvironmentName == transaction.EnvironmentName);
                if (nodeExists)
                {
                    ModelState.AddModelError("EnvironmentName", "Environment already Exists !");
                }

                if (ModelState.IsValid)
                {
                    Environment environment = new Environment();

                    if (environment != null)
                    {
                        environment.EnvironmentID = transaction.EnvironmentID;
                        environment.EnvironmentName = transaction.EnvironmentName;
                        environment.NodeID = transaction.NodeID;
                        environment.EnvironmentPath = transaction.EnvironmentPath;

                        var success = businessComponent.SaveEnvironment(environment);
                    }

                    return RedirectToAction("EnvironmentView");
                }
                transaction.NodesList = businessComponent.GetNodeList();
                return View(transaction);
            }
            catch (Exception ex)
            {
                int ErrorId = ErrorLoggingBusinessComponent.SendExcepToDB(ex);
                return RedirectToAction("Error", "Home");
            }
        }
        #endregion

        #region Uprocs
        public ActionResult UprocsView()
        {
            try
            {
                UprocsModel uprocs = businessComponent.GetUprocs();
                uprocs = SetUprocsReferenceData(uprocs);
                ViewBag.JobRef = uprocs.JobTypeReferenceData;
                ViewBag.EnvironmentRef = uprocs.EnvironmentReferenceData;
                ViewBag.AccountRef = uprocs.AccountTypeReferenceData;
                ViewBag.IsActive = GetIsActiveValues();
                if (uprocs.UprocsList.Any())
                {
                    foreach (var item in uprocs.UprocsList)
                    {
                        item.JobTypeName = uprocs.JobTypeReferenceData.Where(x => x.RefId == item.JobTypeID).FirstOrDefault().RefValue;
                        item.AccountName = uprocs.AccountTypeReferenceData.Where(x => x.RefId == item.AccountTypeID).FirstOrDefault().RefValue;
                        item.EnvironmentName = uprocs.EnvironmentReferenceData.Where(x => x.RefId == item.EnvironmentID).FirstOrDefault().RefValue;
                    }
                }
                return View("UprocsView", uprocs);
            }
            catch (Exception ex)
            {
                int ErrorId = ErrorLoggingBusinessComponent.SendExcepToDB(ex);
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UprocsView(UprocsModel model)
        {
            try
            {
                UprocsModel uprocs = new UprocsModel();
                uprocs = SetUprocsReferenceData(uprocs);
                ViewBag.JobRef = uprocs.JobTypeReferenceData;
                ViewBag.EnvironmentRef = uprocs.EnvironmentReferenceData;
                ViewBag.AccountRef = uprocs.AccountTypeReferenceData;
                ViewBag.IsActive = GetIsActiveValues();
                model.EnvironmentName = uprocs.EnvironmentReferenceData.FirstOrDefault(x => x.RefId == model.EnvironmentID).RefValue;
                ModelState.Remove("UprocsList");
                ModelState.Remove("JobTypeReferenceData");
                ModelState.Remove("EnvironmentReferenceData");
                ModelState.Remove("AccountTypeReferenceData");
                if (ModelState.IsValid)
                {
                    uprocs.UprocID = model.UprocID;
                    uprocs.EnvironmentID = model.EnvironmentID;
                    uprocs.JobTypeID = model.JobTypeID;
                    uprocs.AccountTypeID = model.AccountTypeID;
                    uprocs.UprocName = model.UprocName;
                    uprocs.EnvironmentName = model.EnvironmentName;
                    uprocs.FolderPath = model.FolderPath;
                    uprocs.Command = model.Command;
                    uprocs.IsActive = model.IsActive;
                    businessComponent.SaveUprocDetails(uprocs);
                    return RedirectToAction("UprocsView");
                }
                ViewBag.JobRef = uprocs.JobTypeReferenceData;
                ViewBag.EnvironmentRef = uprocs.EnvironmentReferenceData;
                ViewBag.AccountRef = uprocs.AccountTypeReferenceData;
                var obj = businessComponent.GetUprocs();
                if (obj.UprocsList.Any())
                {
                    model.UprocsList = new List<Uprocs>();
                    foreach (var item in obj.UprocsList)
                    {
                        model.UprocsList.Add(item);
                    }
                }
                return View(model);
            }
            catch (Exception ex)
            {
                int ErrorId = ErrorLoggingBusinessComponent.SendExcepToDB(ex);
                return RedirectToAction("Error", "Home");
            }
        }
        #endregion

        #region Session
        public ActionResult SessionsView()
        {
            try
            {
                SessionsModel sessionsModel = businessComponent.GetSessions();
                sessionsModel = SetSessionsReferenceData(sessionsModel);
                ViewBag.UprocsRef = sessionsModel.UprocsReferenceData;
                ViewBag.EnvironmentRef = sessionsModel.EnvironmentReferenceData;
                ViewBag.UserRef = sessionsModel.UserReferenceData;
                ViewBag.SessionsRef = sessionsModel.SessionsReferenceData;
                ViewBag.DependentUprocs = sessionsModel.DependentUprocsReferenceData;
                if (sessionsModel.SessionsList.Any())
                {
                    foreach (var item in sessionsModel.SessionsList)
                    {
                        item.Uproc = sessionsModel.UprocsReferenceData.Where(x => x.RefId == item.UprocId).FirstOrDefault().RefValue;
                        item.User = sessionsModel.UserReferenceData.Where(x => x.RefId == item.AccountTypeID).FirstOrDefault().RefValue;
                        item.Environment = sessionsModel.EnvironmentReferenceData.Where(x => x.RefId == item.EnvironmentID).FirstOrDefault().RefValue;
                    }
                }
                return View("SessionsView", sessionsModel);
            }
            catch (Exception ex)
            {
                int ErrorId = ErrorLoggingBusinessComponent.SendExcepToDB(ex);
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SessionsView(SessionsModel model, string command)
        {
            try
            {

WebSolution/DSchedule.Web/Controllers/JobMonitoringController.cs
using DSchedule.BusinessComponent;
using DSchedule.Contracts.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DSchedule.Web.Controllers
{
    public class JobMonitoringController : Controller
    {
        DScheduleBusinessComponent businessComponent = new DScheduleBusinessComponent();
     
        // GET: JobMonitoring
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NewUpdateJobView()
        {
            NewUpdateJob nm = businessComponent.GetJob();
            return View("NewUpdateJobView", nm);
        }

        [HttpPost]
        public ActionResult SaveUpdateJob(NewUpdateJob model)
        {
            if (model != null)
            {
                var success = businessComponent.SaveJob(model);
            }

            return RedirectToAction("NewUpdateJobView");
        }
    }
}

WebSolution/DSchedule.Web/Views/JobMonitoring/NewUpdateJobView.cshtml
@{
    ViewBag.Title = "NewUpdateJobView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DSchedule New/Update Job</h2>
<html>
<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>
    @*<script language="javascript">
            function CallMyFunc() {
                $('#newnode').val(null);
            }
        </script>*@
    <script src="@Url.Content("~/Scripts/NewUpdateJob.js")"></script>
</head>
<body>
    <div class="container-fluid">
        @model DSchedule.Contracts.Models.NewUpdateJob

        @using GridMvc.Html
        @*@{
                ViewBag.Title = "Details";
            }
            @{
                Layout = null;
            }*@

        @Html.Grid((List<DSchedule.Contracts.Models.NewUpdateJobModel>)Model.NewUpdateJobs).Named("environmentGrid").Columns(columns =>
   {
       columns.Add(c => c.JobRuleId, true).Titled("JobRule ID").Filterable(false).Css("style: Hide");
       columns.Add(c => c.UprocId, true).Titled("Uproc ID").Filterable(false).Css("style: Hide");
       columns.Add(c => c.UprocName).Titled("Uprocs").Filterable(true);
       columns.Add(c => c.SessionId, true).Titled("Session ID").Filterable(false).Css("style: Hide");
       columns.Add(c => c.SessionName).Titled("Session").Filterable(false);
       columns.Add(c => c.EnvironmentId, true).Titled("Environment ID").Filterable(false).Css("style: Hide");
       columns.Add(c => c.EnvironmentName).Titled("Environment").Filterable(false);
       columns.Add(c => c.NodeId, true).Titled("Node ID").Filterable(false).Css("style: Hide");
       columns.Add(c => c.NodeName).Titled("Node").Filterable(false);
       columns.Add(c => c.ScheduledStartDate).Titled("Scheduled Date/Time").Filterable(true);
       columns.Add(c => c.StartedDateTime).Titled("Started Date/Time").Filterable(true);
       columns.Add(c => c.CompletedDateTime).Titled("Completed Date/Time").Filterable(true);
       columns.Add(c => c.CreatedBy).Titled("Created By").Filterable(true);
       columns.Add(c => c.CreateDate).Titled("Created Date").Filterable(true);
       columns.Add(c => c.UpdatedBy).Titled("Updated By").Filterable(true);
       columns.Add(c => c.UpdateDate).Titled("Updated Date").Filterable(true);
       //columns.Add()
       //.Encoded(false)
       //.Sanitized(false)
       //.SetWidth(30)
       //.RenderValueAs(o => Html.Label("Edit")).Css("text-decoration: underline");
       //"Edit", "Edit", new { id = o.EnvironmentID }));

   }).WithPaging(7).Sortable(true)
    </div>
    <div style="height: 40px; width:100%"></div>
    <div class="container-fluid">
        @using (Html.BeginForm("SaveUpdateJob", "JobDesign", FormMethod.Post, new { transaction = Model }))
        {
            <div class="form-horizontal well">
                <div class="form-group">
                    <label for="UprocID" class="col-md-1">Uproc</label>
                    <div class="col-md-2">
                        @{
                            List<SelectListItem> listItems = new List<SelectListItem>();
                            Model.UprocsList.ForEach(x => listItems.Add(new SelectListItem { Text = x.UprocName, Value = x.UprocID.ToString() }));
                        }
                        @Html.DropDownListFor(model => Model.UprocId, listItems, new { @Class = "form-control", @id = "UprocID" })
                        @Html.HiddenFor(model => Model.JobRuleId, new { @Class = "form-control", @id = "JobRuleId" })
                    </div>
                    <label for="SessionId" class="col-md-1">Session</label>
                    <div class="col-md-2">
                        @{
                            List<SelectListItem> listItems1 = new List<SelectListItem>();
                            Model.SessionsList.ForEach(x => listItems1.Add(new SelectListItem { Text = x.Session, Value = x.SessionId.ToString() }));
                        }
                        @Html.DropDownListFor(model => Model.SessionId, listItems1, new { @Class = "form-control", @id = "SessionId" })
                    </div>
                    <label for="EnvironmentID" class="col-md-1">Environment</label>
                    <div class="col-md-2">

                        @{
                            List<SelectListItem> listItems2 = new List<SelectListItem>();
                            Model.EnvironmentList.ForEach(x => listItems2.Add(new SelectListItem { Text = x.EnvironmentName, Value = x.EnvironmentID.ToString() }));
                        }
                        @Html.DropDownListFor(model => Model.EnvironmentId, listItems2, new { @Class = "form-control", @id = "EnvironmentID" })
                    </div>
                </div>

                <div class="form-group">

                    <label for="startDate" class="col-md-1">Job Start Date/Time:</label>
                    <div class="col-md-2">
                        @{
                            List<SelectListItem> listItems3 = new List<SelectListItem>();
                            Model.UprocsList.ForEach(x => listItems3.Add(new SelectListItem { Text = x.UprocName, Value = x.UprocID.ToString() }));
                        }
                        @Html.DropDownListFor(model => Model.UprocId, listItems3, new { @Class = "form-control", @id = "startDate" })
                    </div>
                    <div class="col-md-2">

                        @*@{
                                List<SelectListItem> listItems1 = new List<SelectListItem>();
                                Model.SessionsList.ForEach(x => listItems1.Add(new SelectListItem { Text = x.Session, Value = x.SessionId.ToString() }));
                            }
                            @Html.DropDownListFor(model => Model.SessionId, listItems1, new { @id = "SessionId" })*@
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        <input type="button" class="btn btn-primary" value="New Job" name="btnNewNode" onclick="NewJob()" />
                    </div>

                    <div class="col-md-2">
                        <input name="btnSave" class="btn btn-primary" type="submit" value="Save" />
                    </div>
                    <div class="col-md-2">
                        <input id="btnCancel" class="btn btn-primary" type="button" value="Cancel" />
                    </div>


                </div>
            </div>
                            }
    </div>
</body>
</html>